version: "3.9"

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    ports:
      - "55000:80"

  db:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  web:
    container_name: web_app
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - redis

  rq:
    build: .
    command: python manage.py rqworker default
    links:
      - redis
    volumes:
      - .:/app

volumes:
  pg_data:
