version: "3.9"

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    ports:
      - "55000:80"

  db:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456


volumes:
  pg_data:
