# Generated by Django 3.2.10 on 2022-04-27 16:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название принтера')),
                ('api_key', models.CharField(max_length=255, verbose_name='ключ доступа к API')),
                ('check_type', models.CharField(choices=[('kitchen', 'Кухня'), ('client', 'Клиент')], default='kitchen', max_length=7, verbose_name='Тип чека, которые печатает принтер')),
                ('point_id', models.IntegerField(db_index=True, verbose_name='Точки, к которым привязаны принтеры')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kitchen', 'Кухня'), ('client', 'Клиент')], default='kitchen', max_length=7, verbose_name='Тип чека')),
                ('order', models.JSONField(verbose_name='Информация о заказе')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('rendered', 'Отображенный'), ('printed', 'Распечатанный')], default='new', max_length=8, verbose_name='Статус чека')),
                ('pdf_file', models.FileField(blank=True, upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Ссылка на созданный PDF-файл')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_model', to='app_check_generation.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
    ]
